# Option-1 : Creating docker container using command module 
---
- hosts: all
  become: true

  tasks:
  - name: Creating docker image using docker command
    command: docker run -d --name car-brand-choice-container -p 8080:8080 car-brand-choice:v1.0.0
	
# option-2 : Creating docker container using docker_container module 	
#  tasks:
#  - name: Create car-brand-choice-container
#    docker_container:
#      name: car-brand-choice-container
#      image: car-brand-choice
#      state: present
#      recreate: yes
#      ports:
#        - "8080:8080"
