# Pull tomcat image from dockerhub 
From ngostal/rockylinux9:tomcat10

# Maintainer
LABEL ORGANIZATION="UNIXCLOUDTRAININGS" 

# copy war file on to container 
COPY ./webapp.war /usr/local/tomcat/webapps
