---
- name: Build and push our docker image to the DockerHub Registry
  hosts: docker
  #become: true
  vars_files:
    - /opt/ansible/docker_vars.yaml # The ansadmin user must have the right permission to access this file and ansible will attend to read it during the ansible playbook execution
  vars:
    major_v: 1
    minor_v: 0
    build_num: 0

  tasks:
  - name: Stop if we have old docker containers running
    command: docker stop car-brand-choice-container
    ignore_errors: yes # To ignore errors if the container does not run/exist

  - name: Remove stopped docker container
    command: docker rm car-brand-choice-container
    ignore_errors: yes # To ignore errors if the container does not exist

  - name: Remove current docker image
    command: docker rmi "car-brand-choice:v{{ major_v }}.{{ minor_v }}.{{ build_num }}"
    ignore_errors: yes # To ignore errors if the image does not exist
#    register: result
#    failed_when:
#      - result.rc == 0
#      - '"docker" not in result.stdout'

  - name: Building docker image
    command: docker build -t car-brand-choice .
    args:
      chdir: /opt/docker # This is where we chose our Dockerfile to reside in.

  - name: Create tag to image
    command: docker tag car-brand-choice "ngostal/car-brand-choice:v{{ major_v }}.{{ minor_v }}.{{ build_num }}"

  - name: Login to your DockerHub account
    command: docker login -u "{{ docker_username }}" -p "{{ docker_passwd }}"
#   /opt/ansible/docker_vars.yaml must be encrypted with ansible vault and can have the following entries
#   docker_username: your_dockerhub_username
#   docker_passwd: your_dockerhub_password

  - name: Push image onto DockerHub
    command: docker push "ngostal/car-brand-choice:v{{ major_v }}.{{ minor_v }}.{{ build_num }}"

  - name: Remove docker images from docker server
    command: docker rmi car-brand-choice "ngostal/car-brand-choice:v{{ major_v }}.{{ minor_v }}.{{ build_num }}"
    ignore_errors: yes

  - name: Log out from your DockerHub Account
    command: docker logout
