---
- name: Create pods using deployment
  hosts: k8s-bootstrap-server
  #become: true
  #user: root

  tasks:
  - name: Create a deployment
    command: kubectl apply -f k8s-uct-deploy.yml

  # - name: Update deployment with new pods if image updated in docker hub
  #   command: kubectl rollout restart deployment.v1.apps/uct-car-deployment

